# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HW9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HW9

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SwiftSpinner'
pod 'Charts'
pod 'XLPagerTabStrip', '~> 9.0'
pod 'Toast-Swift', '~> 5.0.0'

  target 'HW9Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HW9UITests' do
    # Pods for testing
  end

end
